# Generated by Django 3.2.7 on 2021-09-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codingwars', '0003_auto_20210926_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectnames',
            name='urok',
        ),
        migrations.AddField(
            model_name='uroki',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codingwars.subjectnames'),
        ),
    ]
